version: '3.4'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: db
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD
  api:
    build:
      context: .
      dockerfile: DOCKERFILE.api
    image: api_staging
    command: ./bin/travis-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PROJECT_NAME
      - DEBUG=False
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
